Design system - StudyPreview
mash-up-kr/MOIT-iOS pull request #41
Opened 2023-06-11 23:56 UTC by chansooo

# What is this PR? 🔍
- **이슈** : #34 
- **관련 문서** : ❌ 

# Changes 📝
- StudyPreview 구현
- `addOptionalItem` 구현
- secondary color (orange100, orange200) 추가

# Screenshot 📸

<img width="326" alt="스크린샷 2023-06-12 오전 8 53 17" src="https://github.com/mash-up-kr/MOIT-iOS/assets/89574881/117d2e93-bd4c-4130-9c7f-a158b79f6cd5">
<img width="317" alt="스크린샷 2023-06-12 오전 8 53 30" src="https://github.com/mash-up-kr/MOIT-iOS/assets/89574881/901e5af4-5e1c-4901-aba3-bd3623d670cc">

# To Reviewers 🙏
현재 프로필 이미지 오른쪽의 정보들이 있는 item이 margin이 정확하지 않아 보입니다...
혹시 코드에 잘못된 부분이나 수정해야하는 부분이 있다면 말씀해주시면 고치겠습니다

2023-06-12 02:27 UTC, hope1053 commented on DesignSystem/Sources/Common/Flex+.swift
> +    func addOptionalItem(_ view: UIView?) -> Flex {
👍👍 optional view 들어가는 부분에 이 코드 적용하면 좋을 것 같아요~!

2023-06-12 02:55 UTC, hope1053 commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +                        flex.addItem()
![image](https://github.com/mash-up-kr/MOIT-iOS/assets/22907483/dbb8a0c6-b8c9-48b1-9787-c8d776d8b780)

![image](https://github.com/mash-up-kr/MOIT-iOS/assets/22907483/70995736-1fee-44c2-a39f-1e6b93d86949)


지금 요 부분 보면 윗부분이 프로필의 top이랑 맞춰져있는 것 같은데 위 아래 간격이 14로 조금 더 위아래로 붙어야할 것 같아요!
그리고 Figma의 각 chip과 Label의 높이가 지금 구현돼있는거랑 달라서용
간격은 잘 설정해주셨는데 chip과 label의 높이도 고려해서 수정해주셔야 할 것 같습니닷! (스터디명 어차피 다 한 줄로 들어갈 것 같은데 그럼 height만 설정해주면 되지 않을까요?👀)

2023-06-12 04:45 UTC, hope1053 commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +        case .ended:
이 부분 그때 고민이라고 하셨던거 생각나서 좀 고쳐봤는데...
```suggestion
        case .began:
		if translation.x < 0 {
			let translationX = flexRootView.transform.tx < 0 ? flexRootView.transform.tx : translation.x
			
			flexRootView.transform = CGAffineTransform(
				translationX: translationX,
				y: 0
			)
		}
	case .changed:
		if translation.x < 0 && translation.x < flexRootView.transform.tx {
			flexRootView.transform = CGAffineTransform(translationX: translation.x, y: 0)
		}
```
요렇게 고치면

![Simulator Screen Recording - iPhone 14 Pro - 2023-06-12 at 13 40 05](https://github.com/mash-up-kr/MOIT-iOS/assets/22907483/44aabb12-a5f5-4ea6-b759-3d380d0e09d0)

이렇게 되긴하는데 완벽하진 않아서 그냥 참고하시면 좋을 것 같슴다 !

2023-06-12 04:48 UTC, hope1053 commented on DesignSystem/Sources/StudyPreview/StudyPreviewModel.swift
> +public struct StudyPreviewModel {
요 ViewModel은 View 구성 시 사용하지 않는건가용?👀

2023-06-12 04:48 UTC, hope1053 commented on DesignSystem/Sources/StudyPreview/StudyPreviewModel.swift
> +extension StudyPreviewModel: Hashable {
Hashable 채택해놓으신 이유도 궁금합니다!

2023-06-12 04:49 UTC, hope1053 requested changes
👍👍 수고하셨습니다! 레이아웃만 조금 더 수정하면 좋을 것 같아요~! 그리고 파라미터 두 개이상은 줄바꿈으로 맞춰주시면 좋을 것 같습니다!

2023-06-13 01:33 UTC, SongSeoYoung approved these changes
굿굿 이걸 해내다니 ~~! 몇 가지 궁금한 사항들 코멘트 달았슴니다

2023-06-13 01:33 UTC, SongSeoYoung commented on DesignSystem/DemoApp/Sources/StudyPreview/StudyPreviewDemoViewController.swift
> +                    .width(80%)
hoxy 80%라는 수치는 어떻게 계산된건가요??

2023-06-13 01:33 UTC, SongSeoYoung commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +        self.layoutIfNeeded()
굳이 지금 당장 레이아웃 다시 그려 ! 를 할 필요가 있나용 ? setNeedsLayout으로도 충분해보여서요 !

2023-06-13 01:33 UTC, SongSeoYoung commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +                        flex.addItem()
제가 지금 모바일로 코드 리뷰 중이어서 그럴 수도 있는데 여기 캡쳐본 보니까 19의 9가 약간 잘리는 듯 하네요 .. ?! ㅠㅠ

2023-06-13 01:33 UTC, SongSeoYoung commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +                                flex.addItem()
여기는 왜 한 번 더 뎁스를 둔건가요 ?!

2023-06-13 01:33 UTC, SongSeoYoung commented on DesignSystem/Sources/StudyPreview/TouchThroughView.swift
> +class TouchThroughView: UIView {
이 뷰의 의미는 뭔가요 ?!! final! 사라졌따 !

2023-06-13 01:33 UTC, SongSeoYoung commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +    fileprivate let deleteConfirmSubject = PublishSubject<Void>()
subject여야할 이유가 있을까요 !!! 에러가 없을 것 같아서 relay쓰는 것을 고려해도 좋을 것 같지만 just 의견입니당 ~ (반영x여도됨!)

2023-06-13 01:37 UTC, chansooo commented on DesignSystem/DemoApp/Sources/StudyPreview/StudyPreviewDemoViewController.swift
> +                    .width(80%)
에 이건 딱 붙어있으면 보기 힘들어서 그냥 띄워둔겁니당
테스트할 때 양쪽에 여백 있는 게 보기 편할 것 같아서요!

2023-06-13 01:40 UTC, chansooo commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +                                flex.addItem()
오잉 잘리는 부분 아마 수정 전 코드일 거에요!

뎁스는 피그마 보시면 밑에 두개 정보는 붙어있고 뱃지 사이에는 간격이 있어서 이렇게 했습니다

2023-06-13 02:53 UTC, chansooo commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +        self.layoutIfNeeded()
오 한번 확인해보겠습니다 :)

2023-06-13 03:01 UTC, chansooo commented on DesignSystem/Sources/StudyPreview/TouchThroughView.swift
> +class TouchThroughView: UIView {
이거는 버튼이 뷰에 벗어나서 존재하게 되는데(오른쪽에) 이렇게 point override해서 버튼의 위치에 따라서 클릭되었다고 알려주지 않으면 뷰 밖에 있던 버튼이 눌리지 않습니다!
그래서 button 가지고 있는 뷰 만들어서 진행했습니다 :)

2023-06-13 03:03 UTC, chansooo commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +    fileprivate let deleteConfirmSubject = PublishSubject<Void>()
오히려 error가 안 넘어올 것 같아서 subject 래핑한 relay로 error 무시처리하지 않고 그대로 사용하도록 했습니다!

2023-06-13 03:05 UTC, chansooo commented on DesignSystem/Sources/StudyPreview/StudyPreviewModel.swift
> +public struct StudyPreviewModel {
tableViewAdapter처럼 만들어서 사용할까 해서 지금 임시로 만들어놨습니다. 시간 남으면 구현해보려구요~

2023-06-13 03:16 UTC, chansooo commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +        self.layoutIfNeeded()
setNeedsLayout이랑 layoutIfNeeded 없이 markDirty만 해도 상관 없을 것 같은데 어떻게 생각하시나요~?
그리고 요 상황에서 setNeedsLayout이랑 layoutIfNeeded이랑 차이가 있을가요?! 질문입니다!
@SongSeoYoung

2023-06-13 05:43 UTC, hope1053 commented on DesignSystem/Sources/StudyPreview/MOITStudyPreview.swift
> +                        flex.addItem()
> 제가 지금 모바일로 코드 리뷰 중이어서 그럴 수도 있는데 여기 캡쳐본 보니까 19의 9가 약간 잘리는 듯 하네요 .. ?! ㅠㅠ

오 ...이부분은 제가 수정해놓겠습니다🤧

2023-06-13 05:51 UTC, hope1053 approved these changes
수고하셨습니다!
근데 여기서 전자군단 스터디라는 타이틀이 갖고 있는 영역이랑 
![image](https://github.com/mash-up-kr/MOIT-iOS/assets/22907483/58f62a01-1710-4ba1-bde5-4accd0dd7768)
실제로 구현된 부분이랑 좀 차이가 있어서 지금 Chip이랑 타이틀 간 간격이 넓게 보이는 것 같거든요! (하단 description 높이도 마찬가지입니당)
요 부분 레이아웃 조금만 더 수정해주시면 좋을 것 같아요!! 👍👍
![image](https://github.com/mash-up-kr/MOIT-iOS/assets/22907483/9aea53de-3b7f-4818-8102-65faa469c95b)

2023-06-13 06:44 UTC, merged