Feature/web view layer
mash-up-kr/MOIT-iOS pull request #8
Opened 2023-05-28 08:44 UTC by SongSeoYoung

# What is this PR? 🔍
- **이슈** : #3 웹
- **관련 문서** : x

# Changes 📝
MOITWeb 이라는 이름으로 웹뷰 입니다. build할 때 path값만 넣으면 웹뷰 렌딩되도록 구현했습니다. 웹팀과 합의하에 결정된 내용인 safe area까지 웹뷰컨텐츠 영역이 되도록 만들었습니다. 추후 message가 결정되면 앱에서 컨트롤하는 코드 추가하면됩니다 !

demo app에서 확인할 수 있습니다 😲

# Screenshot 📸
![Simulator Screen Recording - iPhone 14 Pro - 2023-05-28 at 17 41 09](https://github.com/mash-up-kr/MOIT-iOS/assets/42825223/f8597d4f-703c-45b1-8ec1-4cad0943a268)

# To Reviewers 🙏

2023-05-29 16:06 UTC, chansooo requested changes
pinlayout, flexlayout dependency때문에 빌드가 정상적으로 안돼서 action 통과가 안됐나보네요!
내일 한번 확인해보고 현재 코드에 문제 있는지 확인해보겠습니다.
빌드가... 안돼서... request change....
수고하셨습니다 👍👏

2023-05-29 16:06 UTC, chansooo commented on Tuist/Features/MOITWeb/DemoApp/Sources/MOITWebDemoRootViewController.swift
> +        print(cell)
로깅 모듈 얼른 추가해두겠습니당.
그 전까지는 debugPrint 어떤가영?

2023-05-29 16:06 UTC, chansooo commented on Tuist/Features/MOITWeb/DemoApp/Sources/MOITWebDemoTableViewCell.swift
> +    }
설정 메소드 접두어 configure로 통일하기로 했었던 것 같은데 기억이 잘 안 나네요

2023-05-29 16:06 UTC, chansooo commented on Tuist/Features/MOITWeb/Implement/MOITWebViewController.swift
> +        static let domain = "https://entertain.naver.com"
static인 이유가 뭘까요~?

2023-05-29 16:06 UTC, chansooo commented on Tuist/Features/MOITWeb/Implement/MOITWebViewController.swift
> +            .value: "어딘가에서 가지고 온 토큰값"  // TODO: 합의 후 수정 필요
토큰 받아오는 usecase 만든 후에 usecase 통해서 받아오는 로직(interactor에서 usecase가지고 있고)으로 변경하면 어떨까요??
지금은 protocol만 선언해두고 나중에 구현체 구현해도 괜찮을 것 같습니다

2023-05-29 16:06 UTC, chansooo commented on Tuist/ProjectDescriptionHelpers/Settings+Extensions.swift
> +}
xcconfig 파일에 동일한 내용 넣어놔서 따로 설정할 필요가 없긴 합니다.
근데 프로젝트 단에서 값을 넣어주는 거랑 타겟 단에서 값을 넣어주는 차이긴 한데 무슨 차이가 있는지는 저도 잘 모르겠네요?!
아신다면 댓글을..

2023-05-29 16:06 UTC, chansooo commented on Tuist/Features/MOITWeb/Interface/MOITWebPath.swift
> +}
MOITWebPath는 어떤 경우에 필요할까요??? 추가적으로 path가 붙을 경우에 사용되는 걸까요?!
그렇다면 url을 관리하는 endpoint를 하나 만드는 건 어떨까요?!!?

2023-05-29 16:16 UTC, SongSeoYoung commented on Tuist/Features/MOITWeb/DemoApp/Sources/MOITWebDemoRootViewController.swift
> +        print(cell)
헉 이 코드 지우겠습니다 .. 지우는걸 깜빡했습니당 🫡

2023-05-29 16:24 UTC, SongSeoYoung commented on Tuist/Features/MOITWeb/Implement/MOITWebViewController.swift
> +        static let domain = "https://entertain.naver.com"
일단 상수를 enum으로 관리하고자하는 의도때문입니다! (객체를 인스턴스화 할 필요는 없지만 높은 응집도를 가지면 좋을 것 같다고 생각했기때문에..) 
혹시 다른 방법으로 어떤 것을 생각하고계신가요? 👀

2023-05-29 16:24 UTC, SongSeoYoung commented on Tuist/Features/MOITWeb/DemoApp/Sources/MOITWebDemoTableViewCell.swift
> +    }
헉 요거 노션 한 번 다시 찾아볼게요~

2023-05-29 16:24 UTC, SongSeoYoung commented on Tuist/Features/MOITWeb/Implement/MOITWebViewController.swift
> +            .value: "어딘가에서 가지고 온 토큰값"  // TODO: 합의 후 수정 필요
넵 좋은 생각입니당 ~ 👍 인터페이스만 구현해둘게요 ! 
@hope1053  구현체는 로그인하시면서 같이 구현부탁드립니당 ~

2023-05-29 16:24 UTC, SongSeoYoung commented on Tuist/Features/MOITWeb/Interface/MOITWebPath.swift
> +}
일단 저희 프로젝트에서 Path는 무조건 필요할 것이라고 생각했는데요 .. ! (필요가 없는 경우를 고려해야한다면 build할 때 path를 옵셔널로 만들겠습니다!) 혹시 url을 관리하는 endpoint라는 것이 어떤 걸 말씀하시는건가요?! 

** 좀 더 부연설명드리면.. 제가 의도한 바는 예를들어 웹에서 스터디생성 페이지 url이 나오면, 도메인 제외 path부분을 해당 enum에 정의하고, build할 때 위 enum의 case만 넘기면 웹뷰 모듈 내부에서 알아서 동작하게끔 한 것이 의도입니다. 매번 path를 string으로 웹뷰모듈에 넘길 필요 없이 하고싶었습니다.! 사용하는 쪽의 편의성을 위해서요 !

2023-05-29 16:24 UTC, SongSeoYoung commented on Tuist/ProjectDescriptionHelpers/Settings+Extensions.swift
> +}
공부해보겠습니다..

2023-05-30 01:21 UTC, chansooo commented on Tuist/Features/MOITWeb/Interface/MOITWebPath.swift
> +}
enum에 baseUrl을 설정해주고, 각각 case에 대해서 path를 설정해준 다음 `toUrl()`과 같은 함수를 enum 내부에 만들어서  url로 바로 받아서 사용하면 어떨까 했습니다.
`MOITWebaosidj.스터디생성1.toUrl()` 처럼 사용해서 바로 url이나 urlString을 받아올 수 있도록요!

2023-05-30 04:46 UTC, chansooo requested changes
폴더링이 현재 Features 폴더가 앱 상단에 있어야 경로가 알맞게 들어갑니다.
Tuist 파일 안에 Features가 있어서 경로를 못 잡아서 문제가 생기네요.
그냥 scaffold 명령어 만들어드린 걸로 `tuist scaffold Feature --name {featurename} --author {authorname}` 사용해서 만들고, 필요없는 부분은 삭제하는게 나아보입니다 :)
수정해서 푸시해주시면 확인하겠습니다 🙏

2023-05-30 14:23 UTC, SongSeoYoung commented on Tuist/Features/MOITWeb/DemoApp/Sources/MOITWebDemoTableViewCell.swift
> +    }
요거 노션에 컨벤션 찾아보니까 그런 내용을 안정했었네요 ?! 자율에 맡겨도될 것 같은데..  규율을 정해도 좋아요 ~

2023-05-30 14:24 UTC, SongSeoYoung commented on Tuist/Features/MOITWeb/Interface/MOITWebPath.swift
> +}
baseurl이 달라질 것 같지않아서 고정으로 생각하긴했습니다만 .. ! 요거 웹팀이랑 이야기해보고 결정할게요 !

2023-05-31 14:09 UTC, chansooo commented on Tuist/Features/MOITWeb/DemoApp/Sources/MOITWebDemoTableViewCell.swift
> +    }
내일 회의 사항에 추가합시당~!

2023-06-03 06:15 UTC, hope1053 approved these changes
👍👍 수고하셨습니당~ 굿굿

2023-06-03 06:28 UTC, chansooo approved these changes
LGTM

2023-06-13 13:58 UTC, merged